In [10]:
# -*- coding: utf-8 -*-
"""
Created on Wed Sep 30 16:27:22 2020

SyntaxError: EOF while scanning triple-quoted string literal (<ipython-input-10-cb2816cc0f5f>, line 3)

In [ ]:
@author: Akash Ghose
"""

In [ ]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
import random
#import numpy as np

ata = pd.read_csv('uncleaned_data.csv')

In [ ]:
def simplify_job_title(title):
    if all(x in title.lower() for x in ['data', 'scientist']):
        return 'Data Scientist'
    elif (all(x in title.lower() for x in ['research', 'scientist']) or
          all(x in title.lower() for x in ['r&d', 'scientist'])):
        return 'Research Scientist'
    elif (all(x in title.lower() for x in ['data', 'analyst']) or
          all(x in title.lower() for x in ['data', 'analytics'])):
        return 'Data Analyst'
    elif (all(x in title.lower() for x in ['research', 'analyst']) or
          all(x in title.lower() for x in ['r&d', 'analyst'])):
        return 'Research Analyst'
    elif all(x in title.lower() for x in ['data', 'engineer']):
        return 'Data Engineer'
    elif all(x in title.lower() for x in ['machine', 'learning']):
        return 'Machine Learning Engineer'
    elif 'scientist' in title.lower():
        return 'Other Scientist'
    elif 'analyst' in title.lower():
        return 'Other Analyst'
    elif ('instructor' in title.lower()):
        return 'Instructor'
    else: return 'Other'
    
def find_seniority(title):
    if any(x in title.lower() for x in ['sr', 'senior', 'manager', '3', 
                                        'lead', 'principal', ' iii']):
        return 'Senior'
    elif any(x in title.lower() for x in['mid', 'ii', '2']):
        return 'Mid-level'
    elif any(x in title.lower() for x in ['jr', 'junior', ' i ', '1', 'associate', 'entry']):
        return 'Junior'
    else:
        return 'na'
    
def convert_revenue(revenue):
    if revenue=='Unknown / Non-Applicable':
        return 0
    elif revenue=='Less than $1 million (USD)':
        return 1
    elif revenue=='$1 to $5 million (USD)':
        return 2
    elif revenue=='$5 to $10 million (USD)':
        return 3
    elif revenue=='$10 to $25 million (USD)':
        return 4
    elif revenue=='$25 to $50 million (USD)':
        return 5
    elif revenue=='$50 to $100 million (USD)':
        return 6
    elif revenue=='$100 to $500 million (USD)':
        return 7
    elif revenue=='$500 million to $1 billion (USD)':
        return 8
    elif revenue=='$1 to $2 billion (USD)':
        return 9
    elif revenue=='$2 to $5 billion (USD)':
        return 10
    elif revenue=='$5 to $10 billion (USD)':
        return 11
    elif revenue=='$10+ billion (USD)':
        return 12
    else: return 0
    
def convert_revenue_no_unknown(revenue):
    if revenue=='Unknown / Non-Applicable':
        return random.randint(1,12)
    elif revenue=='Less than $1 million (USD)':
        return 1
    elif revenue=='$1 to $5 million (USD)':
        return 2
    elif revenue=='$5 to $10 million (USD)':
        return 3
    elif revenue=='$10 to $25 million (USD)':
        return 4
    elif revenue=='$25 to $50 million (USD)':
        return 5
    elif revenue=='$50 to $100 million (USD)':
        return 6
    elif revenue=='$100 to $500 million (USD)':
        return 7
    elif revenue=='$500 million to $1 billion (USD)':
        return 8
    elif revenue=='$1 to $2 billion (USD)':
        return 9
    elif revenue=='$2 to $5 billion (USD)':
        return 10
    elif revenue=='$5 to $10 billion (USD)':
        return 11
    elif revenue=='$10+ billion (USD)':
        return 12
    else: return 0

In [ ]:
def convert_size(size):
    if size=='Unknown':
        return 0
    elif size=='1 to 50 Employees':
        return 1
    elif size=='51 to 200 Employees':
        return 2
    elif size=='201 to 500 Employees':
        return 3
    elif size=='501 to 1000 Employees':
        return 4
    elif size=='1001 to 5000 Employees':
        return 5
    elif size=='5001 to 10000 Employees':
        return 6
    elif size=='10000+ Employees':
        return 7
    else: return 0
    
def convert_size_no_unknown(size):
    if size=='Unknown':
        return random.randint(1,7)
    elif size=='1 to 50 Employees':
        return 1
    elif size=='51 to 200 Employees':
        return 2
    elif size=='201 to 500 Employees':
        return 3
    elif size=='501 to 1000 Employees':
        return 4
    elif size=='1001 to 5000 Employees':
        return 5
    elif size=='5001 to 10000 Employees':
        return 6
    elif size=='10000+ Employees':
        return 7
    else: return 0

In [ ]:
def convert_size_no_unknown(size):
    if size=='Unknown':
        return random.randint(1,7)
    elif size=='1 to 50 Employees':
        return 1
    elif size=='51 to 200 Employees':
        return 2
    elif size=='201 to 500 Employees':
        return 3
    elif size=='501 to 1000 Employees':
        return 4
    elif size=='1001 to 5000 Employees':
        return 5
    elif size=='5001 to 10000 Employees':
        return 6
    elif size=='10000+ Employees':
        return 7
    else: return 0

In [12]:
#Setting console display options
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

In [13]:
data = pd.read_csv('uncleaned_data.csv')

In [14]:
df = data.drop('Headquarters',1)
df = df.drop('Competitors', 1)
    
#Drops rows with which have Job Description as -1
df = df[df['Job Description'] != '-1']
      
"Salary Parsing"
    
df_missing_salary = df[df['Salary Estimate'] == '-1']
df = df[df['Salary Estimate'] != '-1']
#Drops "(Glassdoor estimate)"
salary = df["Salary Estimate"].apply(lambda x: x.lower().split('(')[0])
#Drops "K" and "$"
salary = salary.apply(lambda x: x.replace("k","").replace("$",""))
#Drop "per hour" and "employer provided"
salary = salary.apply(lambda x: 
                      x.replace('per hour', '').
                      replace('employer provided salary:',''))    
 
#appends 'per hour' and 'employer provided salary:' as features
df['hourly'] = df['Salary Estimate'].apply(
    lambda x: 1 if 'per hour' in x.lower() else 0)
df['employer_provided_salary'] = df['Salary Estimate'].apply(
    lambda x: 1 if 'employer provided salary:' in x.lower() else 0)
#Gets min
df["min_salary"] = salary.apply(lambda x: int((x.split('-')[0])))
#Gets max
df['max_salary'] = salary.apply(lambda x: int(x.split('-')[1]))
#Gets avg
df['avg_salary'] = (df.min_salary + df.max_salary)/2 
#convert hourly to yearly salary
df['min_salary'] = df.apply(lambda x: x.min_salary if x.hourly==0 else x.min_salary*2, axis=1)
df['max_salary'] = df.apply(lambda x: x.max_salary if x.hourly==0 else x.max_salary*2, axis=1)
df['avg_salary'] = df.apply(lambda x: x.avg_salary if x.hourly==0 else x.avg_salary*2, axis=1)
  
"Company Name Parsing"

#Drops the ratings attached to the end of the company names
company_name = df.apply(
    lambda x: x['Company Name'] if x.Rating <0 else 
    x['Company Name'][:-3], axis=1)
df['Company Name'] = company_name

"State parsing"
   
df['location_state'] = df.apply(lambda x: x.Location.split(',')[1],axis=1)
df['location_state'] = df['location_state'].apply(
    lambda x: ' CA' if 'los angeles' in x.lower() else x)

In [16]:
df.columns

Index(['Job Title', 'Salary Estimate', 'Job Description', 'Rating',
       'Company Name', 'Location', 'Size', 'Founded', 'Type of ownership',
       'Industry', 'Sector', 'Revenue', 'hourly', 'employer_provided_salary',
       'min_salary', 'max_salary', 'avg_salary', 'location_state'],
      dtype='object')

In [17]:
'Company age'
current_year = 2020
df['age'] = df.Founded.apply(lambda x: x if x <0 else current_year-x)
    
'Parse Job descrpition'
   
df['description_length'] = df['Job Description'].apply(lambda x: len(x))
    
df['contains_python'] = df['Job Description'].apply(
    lambda x: 1 if 'python' in x.lower() else 0)
df['contains_R'] =  df['Job Description'].apply(
    lambda x: 1 if ' r ' in x.lower() or 
    'r-studio' in x.lower() or 
    'r studio' in x.lower() else 0)
df['contains_big_data'] = df['Job Description'].apply(
    lambda x: 1 if 'big data' in x.lower() or 
    'spark' in x.lower() or 
    'hadoop' in x.lower() else 0)
df['contains_MS'] = df['Job Description'].apply(
    lambda x: 1 if ' ms ' in x.lower() or 
    "master's" in x.lower() or
    "masters'" in x.lower() or 
    "masters" in x.lower() or 
    'master' in x.lower() else 0)
    
"Parsing Job Titles"
    
#Will add a simplified job title column
df['simplified_title'] = df['Job Title'].apply(simplify_job_title)
    
#This will parse job title for info about senority and add it as a column
df['seniority'] = df['Job Title'].apply(find_seniority)
    
#Re-ordering columns for ease of readability
df = df[['Job Title','simplified_title', 'seniority', 'Salary Estimate', 
         'min_salary', 'max_salary', 'avg_salary', 'hourly', 
         'employer_provided_salary', 'Job Description', 'description_length',
         'contains_python', 'contains_R', 'contains_big_data', 'contains_MS',
         'Rating','Company Name', 'Location', 'location_state', 'Size', 'Founded',
         'age', 'Type of ownership', 'Industry', 'Sector', 'Revenue']]
    
    
'Converting catagorical/object data to numeric'
    
#First I have to convert all the objects to catagorical data
df = df.apply(lambda x: x.astype('category') if x.dtype=='object' else x)
    
#Convert revenue to numeric, in order
df['revenue_num'] = df.Revenue.apply(convert_revenue_no_unknown).astype('int64')
df['revenue_num_unknown']= df.Revenue.apply(convert_revenue).astype('int64')
    
#Convert size to numeric, in order
df['size_num'] = df.Size.apply(convert_size_no_unknown).astype('int64')
df['size_num_unknown']= df.Size.apply(convert_size).astype('int64')
    
#Convert all desired catagorical data to numeric
# generate binary values using get_dummies
dum_df = pd.get_dummies(df, columns=["simplified_title", 
                                     'seniority','location_state',
                                         'Type of ownership', 'Sector'])
# merge with main df on key values
df = df.merge(dum_df, how='left')

In [18]:
df.columns

Index(['Job Title', 'simplified_title', 'seniority', 'Salary Estimate',
       'min_salary', 'max_salary', 'avg_salary', 'hourly',
       'employer_provided_salary', 'Job Description',
       ...
       'Sector_Manufacturing', 'Sector_Media', 'Sector_Mining & Metals',
       'Sector_Non-Profit', 'Sector_Oil, Gas, Energy & Utilities',
       'Sector_Real Estate', 'Sector_Retail', 'Sector_Telecommunications',
       'Sector_Transportation & Logistics', 'Sector_Travel & Tourism'],
      dtype='object', length=112)

In [25]:
#Setting console display options
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

In [29]:
column = pd.Series(df.columns)
column

0                                             Job Title
1                                      simplified_title
2                                             seniority
3                                       Salary Estimate
4                                            min_salary
5                                            max_salary
6                                            avg_salary
7                                                hourly
8                              employer_provided_salary
9                                       Job Description
10                                   description_length
11                                      contains_python
12                                           contains_R
13                                    contains_big_data
14                                          contains_MS
15                                               Rating
16                                         Company Name
17                                             Location
18                                       location_state
19                                                 Size
20                                              Founded
21                                                  age
22                                    Type of ownership
23                                             Industry
24                                               Sector
25                                              Revenue
26                                          revenue_num
27                                  revenue_num_unknown
28                                             size_num
29                                     size_num_unknown
30                        simplified_title_Data Analyst
31                       simplified_title_Data Engineer
32                      simplified_title_Data Scientist
33                          simplified_title_Instructor
34           simplified_title_Machine Learning Engineer
35                               simplified_title_Other
36                       simplified_title_Other Analyst
37                     simplified_title_Other Scientist
38                    simplified_title_Research Analyst
39                  simplified_title_Research Scientist
40                                     seniority_Junior
41                                  seniority_Mid-level
42                                     seniority_Senior
43                                         seniority_na
44                                   location_state_ AL
45                                   location_state_ AR
46                                   location_state_ AZ
47                                   location_state_ CA
48                                   location_state_ CO
49                                   location_state_ CT
50                                   location_state_ DC
51                                   location_state_ FL
52                                   location_state_ GA
53                                   location_state_ ID
54                                   location_state_ IL
55                                   location_state_ IN
56                                   location_state_ MA
57                                   location_state_ MD
58                                   location_state_ MI
59                                   location_state_ MN
60                                   location_state_ MO
61                                   location_state_ NC
62                                   location_state_ NH
63                                   location_state_ NJ
64                                   location_state_ NV
65                                   location_state_ NY
66                                   location_state_ OH
67                                   location_state_ OR
68                                   location_state_ PA
69                                   location_state_ RI
70                                   location_state_ SC
71                                   location_state_ TN
72                                   location_state_ TX
73                                   location_state_ UT
74                                   location_state_ VA
75                                   location_state_ WA
76                                   location_state_ WI
77                                   location_state_ WY
78               Type of ownership_College / University
79                  Type of ownership_Company - Private
80                   Type of ownership_Company - Public
81                           Type of ownership_Contract
82                         Type of ownership_Government
83                           Type of ownership_Hospital
84             Type of ownership_Nonprofit Organization
85                 Type of ownership_Other Organization
86            Type of ownership_Private Practice / Firm
87     Type of ownership_Subsidiary or Business Segment
88                                            Sector_-1
89                            Sector_Accounting & Legal
90                           Sector_Aerospace & Defense
91                        Sector_Agriculture & Forestry
92              Sector_Arts, Entertainment & Recreation
93                     Sector_Biotech & Pharmaceuticals
94                             Sector_Business Services
95            Sector_Construction, Repair & Maintenance
96                                     Sector_Education
97                                       Sector_Finance
98                                    Sector_Government
99                                   Sector_Health Care
100                       Sector_Information Technology
101                                    Sector_Insurance
102                                Sector_Manufacturing
103                                        Sector_Media
104                              Sector_Mining & Metals
105                                   Sector_Non-Profit
106                 Sector_Oil, Gas, Energy & Utilities
107                                  Sector_Real Estate
108                                       Sector_Retail
109                           Sector_Telecommunications
110                   Sector_Transportation & Logistics
111                             Sector_Travel & Tourism
dtype: object